// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: nkjangpfvxcnsrncuzeh

class SupabaseConfig {
  static const String supabaseUrl = 'https://nkjangpfvxcnsrncuzeh.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ramFuZ3BmdnhjbnNybmN1emVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxNjk0NzQsImV4cCI6MjA5MDc0NTQ3NH0.bz4o-g56CdCw4CfSJtL9BTV0uQN9AtHLOG_Y27vPiRE';
}
